package by.moon.masterassistant.enums;

public enum UserState {
    NONE,
    START,
    ENTERING_GREETING,
    ENTERING_USER_MENU_MESSAGE,
    ENTERING_CONTACTS_MESSAGE,
    ENTERING_SERVICE_AND_PRICES_MESSAGE,
    ENTERING_NAME_FOR_CONTACT,
    ENTERING_LINK_FOR_CONTACT,
    ENTERING_NAME_FOR_SERVICE,
    SENDING_PHOTO_FOR_SERVICE,
    ENTERING_DESCRIPTION_FOR_SERVICE,
    ENTERING_PRICE_FOR_SERVICE,
    CHOOSING_DAY_FOR_WORKING_DAY,
    CHOOSING_TIME_FROM_FOR_WORKING_DAY,
    CHOOSING_TIME_TO_FOR_WORKING_DAY,
    SENDING_CONTACT,
    ENTERING_COMMENT,
    ENTERING_DEPOSIT,
    ENTERING_WITHDRAW,
    ENTERING_BALANCE_CHANGE_COMMENT
}
